In [3]:
# Upgrading Pip Installer
#!pip3 install --upgrade pip

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 6.4 MB/s eta 0:00:0000:0100:010m
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4


In [36]:
# Installing Dependencies
#!pip3 install tensorflow
#!pip3 install tensorflow-gpu
#!pip3 install pandas
#!pip3 install matplotlib
#!pip3 install sklearn
#!pip3 install gradio jinja2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 11.4 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 552.5/552.5 kB 11.4 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 kB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.9/212.9 kB 4.4 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 21.4 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.5/84.5 kB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 447.0/447.0 kB 9.9 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.2/58.2 kB 2.0 MB/s eta 0:00:00
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
Using legacy 'setup.py install' for ffmpy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pycryptodome, since package 'wheel' is not installed.
Using legacy 'setup.py install' for python-multipart, since package 'wheel' is not installed.
  Running setup.py install for ffmpy ... done
  Running setup.py install for python-multipart ... done
  Running setup.py install for pycryptodome ... done


In [17]:
# Availalbe Pip Libraries
!pip3 list

Package              Version
-------------------- ------------------
appnope              0.1.3
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.5
attrs                21.4.0
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               5.0.0
certifi              2022.6.15
cffi                 1.15.0
charset-normalizer   2.0.12
click                8.1.3
cycler               0.11.0
debugpy              1.6.0
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.4
executing            0.8.3
fastjsonschema       2.15.3
fonttools            4.33.3
glob2                0.7
idna                 3.3
ipykernel            6.13.0
ipython              8.3.0
ipython-genutils     0.2.0
jedi                 0.18.1
Jinja2               3.1.2
joblib               1.1.0
jsonschema           4.5.1
jupyter-client       7.3.1
jupyter-core         4.10.0
jupyterlab-pygments  0.2.2
kiwisolver           1.4.2
lxml                 4.9.0
Mar

In [2]:
# Importing Dependencies
import gradio as gr
import os
import pandas as pd
import tensorflow as tf
import numpy as np

# For graphical representations
from matplotlib import pyplot as plt

# Layers used to build up a deep neural network
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import TextVectorization

# For determining the accuracy of the model
from tensorflow.keras.metrics import CategoricalAccuracy
from tensorflow.keras.metrics import Precision
from tensorflow.keras.metrics import Recall

# One of many ways to create a model, easiest and quickest in this scenario
from tensorflow.keras.models import Sequential


In [6]:
# Importing Data

# 'os.path.join' presents the full file path to the desired data file
dfComments = pd.read_csv(os.path.join('/Users', 'maxencebrette', 'Documents', 'Coding', 'Data', 'train.csv'))

In [7]:
# Verifying that the data has been properly loaded in
dfComments.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [9]:
# Tail end of the dataframe
dfComments.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [10]:
# Retrieving the contents of the very first comment
dfComments.iloc[0]['comment_text']

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [14]:
# Finding some toxic comments
dfComments[dfComments['toxic'] == 1].head()

id                                       comment_text  \
6   0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
12  0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......   
16  0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...   
42  001810bf8c45bf5f  You are gay or antisemmitian? \n\nArchangel WH...   
43  00190820581d90ce           FUCK YOUR FILTHY MOTHER IN THE ASS, DRY!   

    toxic  severe_toxic  obscene  threat  insult  identity_hate  
6       1             1        1       0       1              0  
12      1             0        0       0       0              0  
16      1             0        0       0       0              0  
42      1             0        1       0       1              1  
43      1             0        1       0       1              0

In [16]:
# Retrieving the toxicity value of a comment
dfComments[dfComments.columns[2:]].iloc[6]

toxic            1
severe_toxic     1
obscene          1
threat           0
insult           1
identity_hate    0
Name: 6, dtype: int64

In [21]:
# Pre-Processing The Data

# Splitting the dataset into its comments and their overall features
commentsText = dfComments['comment_text']

# Transforming via '.values' into a numpy array
# Each comment text will have a vector defining as to which sort of toxicity 
## categories they may or may not fall into
commentsFeatures = dfComments[dfComments.columns[2:]].values 

In [26]:
print(dfComments.columns)

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')


In [27]:
print(commentsText.head())

0    Explanation\nWhy the edits made under my usern...
1    D'aww! He matches this background colour I'm s...
2    Hey man, I'm really not trying to edit war. It...
3    "\nMore\nI can't make any real suggestions on ...
4    You, sir, are my hero. Any chance you remember...
Name: comment_text, dtype: object


In [28]:
print(commentsFeatures[0:5])

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [30]:
# Defining the maximum number of words allowed within the vocabulary model's dictionary
## The greater the number, the larger the model
## Each word will be tokenized to a unique number so as to be able to identify it
MAXWORDS = 200000

In [ ]:
# Bringing up documentation
TextVectorization??

In [ ]:
# Initializing the text vectorization layer
## Lowers and removes punctuation
## 'max_tokens': The maximum number of words allowed in terms of vocabulary
## 'output_sequence_length': The maximum allowed input length of a sentence
## 'output_mode': In what format is the word supposed to be map to a number, in this case an integer value
vectorizer = TextVectorization(max_tokens = MAXWORDS,
                               output_sequence_length = 1800,
                               output_mode = 'int')

In [ ]:
# Vectorizer is learning each and every word up to the pre-set maximum within the given comments' text
## The pandas series, essential a signle column file format, is transformed into a numpy array via '.values'
print(type(commentsText))
print(type(commentsText.values))
vectorizer.adapt(commentsText.values)

In [ ]:
# The vectorizer can now transform a passed in sentence passed upon its now established dictionary
print(vectorizer('Today was a great day.')[:5])

In [ ]:
# Creating a vectorized version of all of the comments' text data with the now adapted vectorizer
vectorizedCommentsText = vectorizer(commentsText.values)

In [ ]:
# Checking the lengths of the original and vectorized comments' text data
print(len(commentsText))

# If a sentence was shorter than the 1800 limit word length, than the 
## unused columns are set to a value of 0 via padding
vectorizedCommentsText

In [ ]:
# Creating a TensorFlow data pipeline
## Particularly useful when you have a quantity of data which cannot simply 
### be simultaneously brought into memeory
## MCSHBAP Acronym: Map, Cache, Shuffle, Batch, Prefetch
### Basic data pipeline generation steps

### Initiated either by the 'from_tensor_slices' or 'list_files' method
## 'vectorizedCommentsText': The 'x' value or input features
## 'commentFeatures': The 'y' value or target
dataset = tf.data.Dataset.from_tensor_slices((vectorizedCommentsText, commentsFeatures))

# Chaching the data
dataset = dataset.chache()

# Shuffling the data with a passed in buffer size
dataset = dataset.shuffle(160000)

# Batching the dataset as a series of 16 samples
dataset = dataset.batch(16)

# Helping to prevent bottlenecking
dataset = dataset.prefetch(8)

In [ ]:
# Retrieving one batch of the above data pipeline
## Represented as the vectorized comments' text along with their associated feature labels
batchX, batchY = dataset.as_numpy_iterator().next()

In [ ]:
batchX

In [ ]:
# Vector of value sets
batchX.shape

In [ ]:
batchY

In [ ]:
batchY.shape

In [ ]:
# The length of the dataset in batches
print(len(dataset))

# Partitioning the dataset into the testing, validation and training datasets
## Can extract these partitions directly from the data pipeline
## Rounding percentages of partitioning process to an integer value
## Remembering to skip over those portions already partitioned to not reuse duplicate data and forget the leftovers
train = dataset.take(int(len(dataset) * 0.7))
validation = dataset.skip(int(len(dataset) * 0.7)).take(int(len(dataset) * 0.2))
test = dataset.take(int(len(dataset) * 0.9)).take(int(len(dataset) * 0.1))

# Forward pass, backwards pass, upgrade the gradient

print('Batches Per Partition: ')
print(f'Training: {len(train)}')
print(f'Validation: {len(validation)}')
print(f'Testing: {len(test)}')

In [ ]:
# Creating A Sequential Model
# Model sequential API being instantiated
model = Sequential

# Adding Layers

# Sequences passed down into the embedding layer, acting as a sort of personality test per word, learned as 
## the deep neural network is trained, no need to pass in a pre-existing embedding
# Number of words + 1 do to unknown words being embedded as a whole
# 1 Embedding per word, each being 32 feature values in length
model.add(Embedding(MAXWORDS + 1, 32))

# Bidirectional wrapper for neural layer networks, very important for Natural Language Processing (NLP)
## Allows for information to be passed in both directions as opposed to the default 1
## Important due to how previous words in a sentence can affect meaning of following words
### Example: "I don't have you." 
### If this was read only from left to right, the "don't" would not affect the interpretation of the word 'hate'
### as a toxic value, as opposed to if it can be read from right to left as well
# GPU acceleration needed for an LSTM layer is an activation of 'tanh' as dictated by tensorflow
model.add(Bidirectional(LSTM(32, activation = 'tanh')))

# Feature extractor dense fully connected layers
model.add(Dense(128, activation = 'relu'))
model.add(Dense(256, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))

# Final layer
## Maps to the 6 different outputs possible in terms of the target toxicity
model.add(Dense(6, activation = 'sigmoid'))

In [35]:
print(commentsFeatures.shape)
print(commentsFeatures[0])

(159571, 6)
[0 0 0 0 0 0]


In [ ]:
# Compiling the model
# Using binary crossentropy as opposed to categorical as each output is it's own independent feature
## and not part of a whole, this is essentially a multi output model
model.compile(loss = 'BinaryCrossentropy', optimizer = 'Adam')

In [ ]:
# Bidirectional doubles the number of units within the LSTM layer
model.summary()

In [ ]:
# Training the deep neural network model
## Passing in the training data, how long the desire to train and the validation data
## Loss should be progressively decreasing as training nears completion
model.fit(train, epochs = 10, validation_data = validation)

In [ ]:
# Loss metrics of model training
history.history

In [ ]:
# Plotting change in losses over training epochs
plt.figure(figsize = (8, 5))
pd.DataFrame(history.history).plot()
plt.show()

In [ ]:
# Making Predictions
# The sample text has to be vectorized and the words tokenized for the model to be able to make sense of it
sampleInputText = vectorizer('You freaking suck.')

# A sequence of integers
print(sampleInputText)

In [ ]:
# The model expects a series of values or a batch, not a single value, so the vectorized 
## sample input has to be wrapped within a numpy array
## The input shape for the model and the passed in value must match
print(np.array([sampleInputText]))
print(np.expand_dims(sampleInputText, 0))

#model.predict(np.array([sampleInputText]))

# Cleaner version than above example
sampleResult = model.predict(np.expand_dims(sampleInputText, 0))

In [ ]:
batch = test.as_numpy_iterator().next()
batchX, batchY = test.as_numpy_iterator().next()

In [ ]:
batchY

In [ ]:
(model.predict(batchX) > 0.5).astype(int)

In [ ]:
# Evaluating The Model
# Allows for aggregation of metrics over time as the measurement are iterated over and over again over batches
modelPrecision = Precision()
modelRecall = Recall()
modelCategoricalAccuracy = CategoricalAccuracy()

In [ ]:
# Looping through every single batch
for batch in test.as_numpy_iterator():
    
    # Unpacking the batch
    xTrue, yTrue = batch
    
    # Making the precition
    yHat = model.predict(xTrue)
    
    # Flattening the predictions into one very large vector
    ## Instead of a 6x6 matrix, it becomes a 36x1
    yTrue = yTrue.flatten()
    yHat = yHat.flatten()
    
    # Calculating the metrics for the batch, then updating the existing Key Performance Indicators (KPIs)
    modelPrecision.update_state(yTrue, yHat)
    modelRecall.update_state(yTrue, yHat)
    modelCategoricalAccuracy.update_state(yTrue, yHat)

In [ ]:
# Prinintg Results
print(f'Precision: {modelPrecision.result().numpy()}, Recall: {modelRecall.result().numpy()}, Accuracy: {modelCategoricalAccuracy.result().numpy()}')

In [ ]:
# Saving The Model
model.save('commentToxicityModel.h5')

In [ ]:
# Loading The Model
model = tf.keras.models.load_model('commentToxicityModel.h5')

In [ ]:
# Testing & Gradio Application

In [ ]:
# Function to be connected to Gradio

# A text comment is passed in as an argument
def scoreCommentToxicity(commentText):
    
    # The comment is passed through the vectorizer, tokenizing the words
    # Text is converted into a sequence of numbers
    vectorizedComment = vectorize([commentText])
    
    # The tokenized comment is passed through the model to predict whether or not it is of a toxic nature
    results = model.predict(vectorizedComment)
    
    text = ''
    
    # Unpacks the 'results' by looping through each of the dataframe's columns
    # Prints out whether or not the column's feature is true or false for its associated comment
    for index, column in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(column, results[0][index] > 0.5)
        
    return text

In [ ]:
# Creating The Gradio Interface
## 'fn': The function the Gradio interface makes use of
## 'inputs': The type of input
## 'outputs': The style of output
gradioInterface = gr.Interface(fn = scoreCommentToxicity,
                               inputs = gr.inputs.Textbox(lines = 2, placeholder = 'Comment to be scored.'),
                               outputs = text)

In [ ]:
# Launching The Interface
## If the 'share' value is set to 'True', the gradio application will be made public for a limited amount of time
gradioInterface.launch(share = True)